Check Salsa and the user store for an email address before sending a verification email
datamade/django-salsa-auth pull request #9
Opened 2020-09-03 19:27 UTC by hancush

## Description

See title.

Handles #7, handles #8.

## Testing instructions

- Update requirement on the salaries staging site, and test that it works as expected following the instructions here: https://docs.google.com/document/d/15yjsFpRX8SswXtUeACzzZXsE7qgv4YXLg-FjbfbpYww/edit?usp=sharing

2020-09-03 19:27 UTC, hancush commented on salsa_auth/jinja2/auth_modals.html
> +                            <h3>{{ message|safe }}</h3>
Show the first message as the header.

2020-09-03 19:51 UTC, derekeder requested changes
Looking good, as far as I can tell. Would be good to test this on a staging site.

Had some comments about the message titles, otherwise looks good

2020-09-03 19:51 UTC, derekeder commented on salsa_auth/views.py
> +            message_title = "Sorry we missed you!"
I think having a more informative title here would be helpful so they can take action. Is there any action they can take when their status is 'HARD BOUNCE'? Maybe change this to "We can't verify this email address"

2020-09-03 19:51 UTC, derekeder commented on salsa_auth/views.py
> +            message_title = 'You look familiar!'
Related to the above comment, change this to "Please verify this email" or something similar

2020-09-04 21:32 UTC, derekeder approved these changes
looks good!

2020-09-04 21:34 UTC, merged